Update en_pt
minecraftabnormals/Upgrade-Aquatic pull request #306
Opened 2021-11-16 05:00 UTC by thelegitdolt

last time i swear

2021-11-16 21:13 UTC, SmellyModder requested changes

2021-11-16 21:13 UTC, SmellyModder commented on src/main/resources/assets/upgrade_aquatic/lang/en_pt.json
> +	"tooltip.upgrade_aquatic.spotted_jade_northern_pike": "Pikefish o' Jewels w' Dots o' Polka",
Not indented consistently with the rest of the entries.

2021-11-16 21:13 UTC, SmellyModder commented on src/main/resources/assets/upgrade_aquatic/lang/en_pt.json
> +	"item.minecraft.tipped_Bolt.effect.restfulness_strong": "Bolt o' Clappin' Thunder",
These lines are not indented consistently with the rest of the entries.

2021-11-16 21:13 UTC, SmellyModder commented on src/main/resources/assets/upgrade_aquatic/lang/en_pt.json
> +    "item.upgrade_aquatic.cooked_perch": "Smoked Perch",
These lines are not indented consistently with the rest of the entries.

2021-11-23 21:06 UTC, thelegitdolt commented
made a new pull request that fixes these errors with some more lines updated!

2021-11-23 21:06 UTC, closed without merging